### ISSUE TITLE
hello，I miss 1.12.6，Save it

### ISSUE THREAD

**Issue by 2924223848** [zhuowei/MCPELauncher#1501]
launcher 1.12.6 will not work on android 7.1 or above,So I came into contact with Java,But I still couldn't do it.Please, save it.--cc

**Comment by 2924223848** [comment]
java.lang.IllegalArgumentException: Unable to find native library

**Comment by 2924223848** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.zhuoweizhang.mcpelauncher.pro/net.zhuoweizhang.mcpelauncher.pro.LauncherProActivity}: java.lang.IllegalArgumentException: Unable to find native library minecraftpe using classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/net.zhuoweizhang.mcpelauncher.pro-G0JlwdIoxRqxOZoYb5zogA==/base.apk"],nativeLibraryDirectories=[/data/app/net.zhuoweizhang.mcpelauncher.pro-G0JlwdIoxRqxOZoYb5zogA==/lib/arm, /system/fake-libs, /data/app/net.zhuoweizhang.mcpelauncher.pro-G0JlwdIoxRqxOZoYb5zogA==/base.apk!/lib/armeabi-v7a, /system/lib]]]
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(

**Comment by 2924223848** [comment]
Unable to find native library minecraftpe1 using classloader:
 dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar",
  zip file "/data/app/net.zhuoweizhang.mcpelauncher.pro-glmgrC7I09fcagwrSec_-A==/base.apk"],
  nativeLibraryDirectories=[/data/app/net.zhuoweizhang.mcpelauncher.pro-glmgrC7I09fcagwrSec_-A==/lib/arm, /system/fake-libs,
   /data/app/net.zhuoweizhang.mcpelauncher.pro-glmgrC7I09fcagwrSec_-A==/base.apk!/lib/armeabi-v7a, /system/lib]]]


in ，The path of the library is the path of the initiator, not Minecraft install pack.

**Comment by 2924223848** [comment]
从 Android 7.0 开始，系统将阻止应用动态链接非公开 NDK 库，这种库可能会导致您的应用崩溃。此行为变更旨在为跨平台更新和不同设备提供统一的应用体验。即使您的代码可能不会链接私有库，但您的应用中的第三方静态库可能会这么做。因此，所有开发者都应进行相应检查，确保他们的应用不会在运行 Android 7.0 的设备上崩溃。如果您的应用使用原生代码，则只能使用公开 NDK API。
动态库加载最终会调用这个函数，在这里会判断是否允许加载该动态库，最终就是logcat中显示的异常信息；

作者：NiceDream
链接：https://www.jianshu.com/p/90a9e4a5b47d
來源：简书

**Comment by 2924223848** [comment]
hello，it was fixed.
现在，1.12.6启动器已经修复了

**Comment by zhuowei** [comment]
You're, I think, the 5th person to ask for an updated version of 1.12?
I'm still not sure why you're using such an old version of BlockLauncher, but I'll be happy to help.

The two changes I made to fix BlockLauncher on Android 7 and 8 are here: https://gist.github.com/zhuowei/c1cb4e37bfad09c3393da87699ff81e3

I never ported this back to older versions because I'm not sure if I still can build those older versions. I could translate these to Smali and patch the original APK using ApkTool, but I never got around to it.

Sorry about this and hope this helps.

**Comment by 2924223848** [comment]
Thanks for your reply, thus it can be seen a idea .but my programming level is low, I think of a stupid method,
System.loadLibrary("minecraftpe");
Absolute path,the required lib files are placed in the lib directory of the launcher.
Sorry, I modified your installation package without authorization, but I did not transmit it.
thank your masterpiece!
